name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m venv .venv

          .venv/bin/pip install --upgrade pip
          .venv/bin/pip install pytest
          .venv/bin/pip install -r requirements.txt
          .venv/bin/pip install -e .

      - run: .venv/bin/pytest tests/

      - run: .venv/bin/python -m build
